title                          : Shit Show Development
description                    : > 
   Open-Source Development and Customization
repository                     : tbr-development/docs
baseUrl                        : "/Docs"
url                            : "//shitshowdevelopment.github.io"
show_excerpts                  : false
permalink                      : pretty
remote_theme                   : just-the-docs/just-the-docs
color_scheme                   : "dark"
search_enabled                 : true
search                         :
  heading_level                : 2
  previews                     : 3
  preview_words_before         : 5
  preview_words_after          : 10
  tokenizer_separator          : /[\s/]+/
  rel_url                      : true
  button                       : false
  focus_shortcut_key           : 'k'
enable_copy_code_buttonn       : true
last_edit_timestamp            : true
last_edit_time_format          : "%b %e %Y at %I:%M %p" 
back_to_top                    : true
back_to_top_text               : "Back to top"  
header_pages                   :
  - index.md
  - projects.md
  - links.md
  - 404.md
  - projects/apps.md
  - projects/scripts.md
  - projects/nexus-mods.md
  - projects/discord-bots.md
  - projects/deskthemepacks.md
  - projects/shitshowcogs.md
  - projects/deskthemepacks/classic-windows-ports.md
  - projects/deskthemepacks/studii-ghibli-themes.md
  - projects/deskthemepacks/classic-cartoon-themes.md
  - projects/discord-bots/shitshowsupervisor.md
  - projects/discord-bots/shitshowcoordinator.md
  - projects/scripts/rammap-task-scheduler.md
  - projects/apps/yt-music-player.md
  - projects/nexus-mods/extensions.md
  - projects/shitshowcogs/cogs.md
  - projects/shitshowcogs/instructions.md
plugins                        :
  - jekyll-seo-tag
  - jekyll-github-metadata
kramdown                       :
  syntax_highlighter_opts      :
    block                      :
      line_numbers             : false
